name: Deploy to Github Pages
 
on:
    push:
        branches: [main]
 
permissions: #permissions pour Github Pages
    contents: read
    pages: write
    id-token: write
 
concurrency:
    group: pages
    cancel-in-progress: true
 
jobs:
    ci:
        uses: ./.github/workflows/ci.yml #réutilise le workflow CI existant
        secrets: inherit
 
    deploy:
        needs: ci
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url}}
 
        steps:
            - name: Checkout
              uses: actions/checkout@v4
           
            - name: Setup Pages
              uses: actions/configure-pages@v4
 
            - name: Upload static file
              uses: actions/upload-pages-artifact@v3
              with:
                path: public/
 
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4